# Generated by Django 5.2.7 on 2025-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contactno', models.CharField(verbose_name=15)),
                ('subject', models.CharField(max_length=200)),
                ('enqdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
