# Generated by Django 5.2.7 on 2025-11-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='picutre',
            new_name='picture',
        ),
    ]
